sonar.projectKey=silverconnect-global
sonar.projectName=SilverConnect Global
sonar.projectVersion=0.1.0
sonar.organization=lesliezhili

sonar.sources=app,components,lib,api
sonar.tests=__tests__,e2e
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=node_modules/**,**/*.d.ts,.next/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,e2e/**

sonar.qualitygate.wait=true
