import { NextResponse } from "next/server";
export async function POST() {
  const { default: postgres } = await import("postgres");
  const sql = postgres(process.env.DATABASE_URL || "", { prepare: false, connect_timeout: 10 });
  try {
    await sql`CREATE TABLE IF NOT EXISTS membership_plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT, price_monthly NUMERIC(8,2) DEFAULT 0, price_yearly NUMERIC(8,2) DEFAULT 0, currency TEXT DEFAULT 'AUD', discount_percent INT DEFAULT 0, priority_booking BOOLEAN DEFAULT false, free_cancellations INT DEFAULT 0, gps_tracking BOOLEAN DEFAULT false, photo_reports BOOLEAN DEFAULT false, dedicated_provider BOOLEAN DEFAULT false, max_bookings_month INT, features JSONB DEFAULT '[]', is_active BOOLEAN DEFAULT true, sort_order INT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS memberships (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, plan_id UUID NOT NULL, status TEXT DEFAULT 'active', billing_cycle TEXT DEFAULT 'monthly', start_date DATE DEFAULT CURRENT_DATE, end_date DATE, next_billing_date DATE, stripe_subscription_id TEXT, phledger_subscription_id TEXT, payment_provider TEXT DEFAULT 'phledger', cancelled_at TIMESTAMPTZ, cancel_reason TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS idx_mem_user_active ON memberships(user_id) WHERE status = 'active'`.catch(() => {});
    await sql`CREATE TABLE IF NOT EXISTS membership_usage (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), membership_id UUID NOT NULL, user_id UUID NOT NULL, month TEXT NOT NULL, bookings_used INT DEFAULT 0, cancellations_used INT DEFAULT 0, discount_savings NUMERIC(8,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW())`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_month ON membership_usage(membership_id, month)`.catch(() => {});
    await sql`INSERT INTO membership_plans (code, name, description, price_monthly, price_yearly, discount_percent, priority_booking, free_cancellations, gps_tracking, photo_reports, dedicated_provider, max_bookings_month, sort_order, features) VALUES ('free','Free','Pay-as-you-go, no commitment',0,0,0,false,0,false,false,false,null,0,'["Basic booking","Standard support","Pay per service"]'), ('silver','Silver','Regular home maintenance',29.99,299.99,10,true,2,true,true,false,8,1,'["10% off all services","Priority booking","2 free cancellations/month","GPS tracking","Photo reports"]'), ('gold','Gold','Frequent services',59.99,599.99,20,true,5,true,true,true,20,2,'["20% off all services","Priority booking","5 free cancellations/month","Dedicated provider","20 bookings/month"]'), ('platinum','Platinum','Premium comprehensive care',99.99,999.99,30,true,99,true,true,true,null,3,'["30% off all services","Unlimited cancellations","Dedicated provider","Unlimited bookings","24/7 priority support","Family sharing"]') ON CONFLICT (code) DO NOTHING`;
    await sql.end();
    return NextResponse.json({ success: true, tables: ["membership_plans","memberships","membership_usage"], plans: ["free","silver","gold","platinum"] });
  } catch (err: unknown) { await sql.end().catch(() => {}); return NextResponse.json({ error: err instanceof Error ? err.message : String(err) }, { status: 500 }); }
}
